//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGestionASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartement()
        {
            this.ContratLocation = new HashSet<ContratLocation>();
        }
    
        public int IdAppartement { get; set; }
        public string AdresseAppartement { get; set; }
        public Nullable<double> Surface { get; set; }
        public Nullable<double> Capacite { get; set; }
        public Nullable<int> NombrePiece { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public Nullable<int> IdPropriataire { get; set; }
        public Nullable<int> IdTypeAppartement { get; set; }
    
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual TypeAppartement TypeAppartement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratLocation> ContratLocation { get; set; }
    }
}
