//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGestionASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratLocation()
        {
            this.Paiement = new HashSet<Paiement>();
        }
    
        public int IdContrat { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<double> Montant { get; set; }
        public string Statut { get; set; }
        public Nullable<int> IdAppartement { get; set; }
        public Nullable<int> IdLocataire { get; set; }
        public Nullable<int> IdPaiement { get; set; }
    
        public virtual Appartement Appartement { get; set; }
        public virtual Locataire Locataire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiement { get; set; }
        public virtual Paiement Paiement1 { get; set; }
    }
}
