//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGestionASPNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdappartement1Entities : DbContext
    {
        public bdappartement1Entities()
            : base("name=bdappartement1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Appartement> Appartement { get; set; }
        public virtual DbSet<ContratLocation> ContratLocation { get; set; }
        public virtual DbSet<Locataire> Locataire { get; set; }
        public virtual DbSet<ModePaiement> ModePaiement { get; set; }
        public virtual DbSet<Paiement> Paiement { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Proprietaire> Proprietaire { get; set; }
        public virtual DbSet<TypeAppartement> TypeAppartement { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
