//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGestionASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paiement()
        {
            this.ContratLocation1 = new HashSet<ContratLocation>();
        }
    
        public int IdPaiement { get; set; }
        public Nullable<System.DateTime> DatePaiment { get; set; }
        public Nullable<double> Montant { get; set; }
        public string NumeroFacture { get; set; }
        public Nullable<int> IdModePaiement { get; set; }
        public Nullable<int> IdContrat { get; set; }
    
        public virtual ContratLocation ContratLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratLocation> ContratLocation1 { get; set; }
        public virtual ModePaiement ModePaiement { get; set; }
    }
}
