//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGestionASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int IdPersonne { get; set; }
        public string NomPrenom { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string CNI { get; set; }
    
        public virtual Locataire Locataire { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
